---
title: "analysis_tina"
author: "Tina Liu"
date: "2020/1/13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("outliers")
```

```{r}
library(tidyverse)
```


```{r}
library(outliers)
```


```{r}
chi_square <- function(x, pvalue) {
  while(chisq.out.test(x)$p.value < pvalue) {
    str <- chisq.out.test(x)$alternative
    print(str)
    n <- as.numeric(unlist(regmatches(str,
                                    gregexpr("(?<=value)(.*)(?=is an outlier)", str, perl = T))))
    x <- x[x != n]
    print(length(x))
  }
}
```

```{r}
chi_square(s_norm$value)
```

```{r}
chi_square(SeaSlugs$Percent)
```


```{r}
x <- SeaSlugs$Percent
```



```{r}
while(chisq.out.test(x)$p.value < 0.01) {
  str <- chisq.out.test(x)$alternative
  print(str)
  n <- as.numeric(unlist(regmatches(str,
                                    gregexpr("(?<=value)(.*)(?=is an outlier)", str, perl = T))))
  x <- x[x != n]
  print(length(x))
}
```


```{r}
var(s_norm$value)
```

```{r}
chisq.out.test(s_norm$value, var(s_norm$value))
```


```{r}
plot(cooks.distance(lm(Yards~1, data=TomlinsonRush)))
```


```{r}
str <- quantile(s_norm$value, probs = c(0.25, 0.75))
```

```{r}
str
```



```{r}
iqr <- unname(quantile(s_norm$value, probs = c(0.25, 0.75))[c("25%", "75%")])
```

```{r}
iqr[1]
```

```{r}
try <- iqr[2] - iqr[1]
```

```{r}
try
```


```{r}
IQR_test <- function(data, num, v) {
  str <- unname(quantile(num, probs = c(0.25, 0.75))[c("25%", "75%")])
  iqr <- str[2] - str[1]
  q1 <- str[1] - iqr
  q3 <- str[2] + iqr
  data %>%
    mutate(id = seq.int(nrow(data))) %>%
    select(id, v) %>%
    rename("value" = v) %>%
    mutate(outlier = if_else(value >= q3 | value <= q1, "yes", "no")) %>%
    filter(outlier == "yes")
}
```

```{r}
IQR_test(s_norm, s_norm$value, "value")
```

```{r}
IQR_test(SeaSlugs, SeaSlugs$Percent, "Percent")
```


```{r}
SeaSlugs %>%
  mutate(id = seq.int(nrow(SeaSlugs)))
```


```{r}
s_norm %>% 
  select(value) %>%
  mutate(value = as.numeric(value)) %>%
  mutate(outlier = if_else(value >= 8, "yes", "no"))
```


```{r}
test <- function()
```


```{r}
sd_test <- function(data, num, v) {
  t1 <- mean(num) + 4*sd(num)
  t2 <- mean(num) - 4*sd(num)
  data %>%
    mutate(id = seq.int(nrow(data))) %>%
    select(id, v) %>%
    rename("value" = v) %>%
    mutate(outlier = if_else(value >= t1 | value <= t2, "yes", "no")) %>%
    filter(outlier == "yes")
}
```

```{r}
sd_test(s_norm, s_norm$value, "value")
```


```{r}
mean(s_norm$value) + 2.5*sd(s_norm$value)
```

```{r}
sd_test(SeaSlugs, SeaSlugs$Percent, "Percent")
```



