---
title: "winter_Tina"
author: "Tina Liu"
date: "2020/1/8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("sn")
```


```{r}
library(tidyverse)
library(sn)
```

```{r}
cabinet_5 <- read_csv("cabinet-turnover.csv")
airbnb_6 <- read_csv("listings.csv")
top50_3 <- read_csv("top50.csv")
nfl_1 <- read_csv("nfl_elo.csv")
```

```{r}
airbnb_6 <- airbnb_6 %>% select(price, number_of_reviews)
```

```{r}
cabinet_5 <- cabinet_5 %>% 
  filter(!is.na(length)) %>%
  mutate(length = as.numeric(length))
```




```{r}
nfl_1 <- nfl_1 %>% filter(season >= 2000)
nfl_1 <- nfl_1 %>% select(elo1_post)
```



Dataset 1:
```{r}
glimpse(nfl_1)
D1<- lm(elo1_post~0, data = nfl_1)
summary(D1)
hist(nfl_1$elo1_post)
```


Dataset 2:
```{r}
glimpse(top50_3)
D2 <- lm(Beats.Per.Minute~0, data = top50_3)
summary(D2)
hist(top50_3$Beats.Per.Minute)
```


Dataset 3:
```{r}
glimpse(cabinet_5)
D3 <- lm(length~0, data = cabinet_5)
summary(D3)
hist(cabinet_5$length)
```

```{r}
airbnb_6 <- airbnb_6 %>% mutate(number_of_reviews = as.numeric(number_of_reviews))
```


Dataset 5:
```{r}
glimpse(airbnb_6)
D5 <- lm(number_of_reviews~0, data = airbnb_6)
summary(D5)
hist(airbnb_6$number_of_reviews)
```




```{r}
library(Stat2Data)
```

Dataset 23:
```{r}
data("Kershaw")
D23<-lm(StartSpeed~0, data=Kershaw)
summary(D23)
hist(Kershaw$StartSpeed)
```


Dataset 24:
```{r}
data("SeaIce")
D24<-lm(Extent~0, data=SeaIce)
summary(D24)
hist(SeaIce$Extent)
```


Dataset 25:
```{r}
data("TomlinsonRush")
D25<-lm(Yards~0, data=TomlinsonRush)
summary(D25)
hist(TomlinsonRush$Yards)
```

Dataset 26:
```{r}
data("BlueJays")
glimpse(BlueJays)
D26<-lm(BillDepth~0, data=BlueJays)
summary(D26)
hist(BlueJays$BillDepth)
```


Dataset 27:
```{r}
data("WalkTheDogs")
glimpse(WalkTheDogs)
D27<-lm(Kcal~0, data=WalkTheDogs)
summary(D27)
hist(WalkTheDogs$Kcal)
```


Datset 28:
```{r}
data("SeaSlugs")
glimpse(SeaSlugs)
D28<-lm(Percent~0, data=SeaSlugs)
summary(D28)
hist(SeaSlugs$Percent)
```


Dataset 29:
```{r}
data("Dinosaurs")
glimpse(Dinosaurs)
D29<-lm(Depth~0, data=Dinosaurs)
summary(D27)
hist(Dinosaurs$Iridium)
```


Datset 30:
```{r}
data("Putts1")
glimpse(Putts1)
D30<-lm(Length~0, data=Putts1)
summary(D30)
hist(Putts1$Length)
```


Control Set 1:
```{r}
set.seed(14)
x1 <- rnorm(33, sd = 4)
x1 <- c(x1, 100, -100)
s_norm <- data.frame(id=as.character(1:35), 
                  value=x1, 
                  stringsAsFactors=F)
hist(s_norm$value)
C1<-lm(value~1, data=s_norm)
```


Control Set 2:
```{r}
set.seed(3)
x2 <- rnorm(298, sd = 4)
x2 <- c(x2, 200, -200)
m_norm <- data.frame(id=as.character(1:300), 
                  value=x2, 
                  stringsAsFactors=F)
hist(m_norm$value)
```

Control Set 3:
```{r}
set.seed(5)
x3 <- rnorm(998, sd = 4)
x3 <- c(x3, 300, -300)
l_norm <- data.frame(id=as.character(1:1000), 
                  value=x3, 
                  stringsAsFactors=F)
hist(l_norm$value)
```

Control Set 4:
```{r}
set.seed(12)
x4 <- rsn(33, alpha = 4)
x4 <- c(x4, 100, -100)
s_right <- data.frame(id=as.character(1:35), 
                  value=x4, 
                  stringsAsFactors=F)
hist(s_right$value)
```


Control Set 5:
```{r}
set.seed(6)
x5 <- rsn(298, alpha = 4)
x5 <- c(x5, 100, -100)
m_right <- data.frame(id=as.character(1:300), 
                  value=x5, 
                  stringsAsFactors=F)
hist(m_right$value)
```


Control Set 6:
```{r}
set.seed(14)
x6 <- rsn(998, alpha = 4)
x6 <- c(x6, 100, -100)
l_right <- data.frame(id=as.character(1:1000), 
                  value=x6, 
                  stringsAsFactors=F)
hist(l_right$value)
```

Control Set 7:
```{r}
set.seed(18)
x7 <- rsn(33, alpha = -4)
x7 <- c(x7, 100, -100)
s_left <- data.frame(id=as.character(1:35), 
                  value=x7, 
                  stringsAsFactors=F)
hist(s_left$value)
```

Control Set 8:
```{r}
set.seed(16)
x8 <- rsn(298, alpha = -4)
x8 <- c(x8, 100, -100)
m_left <- data.frame(id=as.character(1:300), 
                  value=x8, 
                  stringsAsFactors=F)
hist(m_left$value)
```

Control Set 9:
```{r}
set.seed(17)
x9 <- rsn(998, alpha = -4)
x9 <- c(x9, 100, -100)
l_left <- data.frame(id=as.character(1:1000), 
                  value=x9, 
                  stringsAsFactors=F)
hist(l_left$value)
```