---
title: "Experiment Procedure"
author: "Alex Khater"
date: "1/15/2020"
output: html_document
---
```{r}
library(Stat2Data)
library(mosaic)
library(car)
library(outliers)
library(tidyverse)
library(moments)
```



```{r}
chi_square <- function (x, pvalue = 0.03, opposite = FALSE) {
    x <- sort(x[complete.cases(x)])
    variance <- var(x)
    mea <- mean(x)
    n <- length(x)
    i <- 1
    pval <- chisq.out.test(x, opposite = opposite)$p.value
    num <- 0
    while(pval < pvalue) {
      if (xor(((x[n] - mea) < (mea - x[i])), opposite)) {
        alt = paste("lowest value", x[i], "is an outlier")
        chi <- (mea - x[i])^2/variance
        i <- i + 1
        }
      else {
        alt = paste("highest value", x[n], "is an outlier")
        chi <- (x[n] - mea)^2/variance
        n <- n - 1
        }
      pval <- 1 - pchisq(chi, 1)
      print(alt)
      num <- num + 1
    }
    print(num)
}
```

```{r}
cook_distance <- function(lm) {
  cooksd <- cooks.distance(lm)
  k <- 4*mean(cooksd)
  data <- data.frame(id=as.character(1:length(cooksd)), 
                  value=cooksd, 
                  stringsAsFactors=F)
  data %>%
    mutate(id = seq.int(nrow(data))) %>%
    mutate(outlier = if_else(value >= k, "yes", "no")) %>%
    filter(outlier == "yes")
}
```


```{r}
IQR_test <- function(data, num, v) {
  str <- unname(quantile(num, probs = c(0.25, 0.75), na.rm = TRUE)[c("25%", "75%")])
  iqr <- str[2] - str[1]
  q1 <- str[1] - 1.5*iqr
  q3 <- str[2] + 1.5*iqr
  data %>%
    mutate(id = seq.int(nrow(data))) %>%
    select(id, v) %>%
    rename("value" = v) %>%
    mutate(outlier = if_else(value >= q3 | value <= q1, "yes", "no")) %>%
    filter(outlier == "yes")
}
```

```{r}
sd_test <- function(data, num, v) {
  t1 <- mean(num) + 2.5*sd(num)
  t2 <- mean(num) - 2.5*sd(num)
  data %>%
    mutate(id = seq.int(nrow(data))) %>%
    select(id, v) %>%
    rename("value" = v) %>%
    mutate(outlier = if_else(value >= t1 | value <= t2, "yes", "no")) %>%
    filter(outlier == "yes")
}
```

```{r}
#Bonferonni
car::outlierTest(LM)
```

Begin Work:

Data1 :
```{r}
chi_square(nfl_1$elo1_post, 0.03)
cook_distance(D1)
IQR_test(nfl_1, nfl_1$elo1_post, "elo1_post")
sd_test(nfl_1, nfl_1$elo1_post, "elo1_post")
```

Data2
```{r}
chi_square(top50_3$Beats.Per.Minute, 0.03)
cook_distance(D2)
IQR_test(top50_3, top50_3$Beats.Per.Minute, "Beats.Per.Minute")
sd_test(top50_3, top50_3$Beats.Per.Minute, "Beats.Per.Minute")

```

Data 3-14 -Tina

Data 15
```{r}
chi_square(LeveeFailures$VegWidth, 0.03)
cook_distance(D15)
IQR_test(LeveeFailures, LeveeFailures$VegWidth, "VegWidth")
sd_test(LeveeFailures, LeveeFailures$VegWidth, "VegWidth")
```
Data 16
```{r}
chi_square(Retirement$SRA, 0.03)
cook_distance(D16)
IQR_test(Retirement, Retirement$SRA, "SRA")
sd_test(Retirement, Retirement$SRA, "SRA")
```
Data 17
```{r}
chi_square(CO2Hawaii$CO2, 0.03)
cook_distance(D17)
IQR_test(CO2Hawaii, CO2Hawaii$CO2, "CO2")
sd_test(CO2Hawaii, CO2Hawaii$CO2, "CO2")
```
Data 18
```{r}
chi_square(Faces$SHR, 0.03)
cook_distance(D18)
IQR_test(Faces, Faces$SHR, "SHR")
sd_test(Faces, Faces$SHR, "SHR")
```

Data 19
```{r}
chi_square(Kids198$Weight, 0.03)
cook_distance(D19)
IQR_test(Kids198, Kids198$Weight, "Weight")
sd_test(Kids198, Kids198$Weight, "Weight")
```
Data 20
```{r}
chi_square(BirdNest$Length, 0.03)
cook_distance(D20)
IQR_test(BirdNest, BirdNest$Length, "Length")
sd_test(BirdNest, BirdNest$Length, "Length")
```
Data 21
```{r}
chi_square(HawkTail$Tail, 0.03)
cook_distance(D21)
IQR_test(HawkTail, HawkTail$Tail, "Tail")
sd_test(HawkTail, HawkTail$Tail, "Tail")
```
Data 22
```{r}
chi_square(AppleStock$Price, 0.03)
cook_distance(D22)
IQR_test(AppleStock, AppleStock$Price, "Price")
sd_test(AppleStock, AppleStock$Price, "Price")
```
Data 23
```{r}
chi_square(Kershaw$StartSpeed, 0.03)
cook_distance(D23)
IQR_test(Kershaw, Kershaw$StartSpeed, "StartSpeed")
sd_test(Kershaw, Kershaw$StartSpeed, "StartSpeed")
```
Data 24
```{r}
chi_square(SeaIce$Extent, 0.03)
cook_distance(D24)
IQR_test(SeaIce, SeaIce$Extent, "Extent")
sd_test(SeaIce, SeaIce$Extent, "Extent")
```

Data 25
```{r}
chi_square(TomlinsonRush$Yards, 0.03)
cook_distance(D25)
IQR_test(TomlinsonRush, TomlinsonRush$Yards, "Yards")
sd_test(TomlinsonRush, TomlinsonRush$Yards, "Yards")

```

```{r}
S1 <- skewness(nfl_1$elo1_post)
S2 <- skewness(top50_3$Beats.Per.Minute)
S3 <- skewness(cabinet_5$length)
S4 <- skewness(Cereal$Sugar)
S5 <- skewness(airbnb_6$number_of_reviews)
S6 <- skewness(SATGPA$MathSAT)
S7 <- skewness(KeyWestWater$WaterTemp)
S8 <- skewness(FirstYearGPA$GPA)
S9 <- skewness(Diamonds2$Carat)
S10 <- skewness(MLBStandings2016$Runs)
```

```{r}
S11 <- skewness(PeaceBridge2012$Traffic)
S12 <- skewness(Perch$Weight)
S13 <- skewness(Houses$Price)
S14 <- skewness(Fertility$E2)
S15 <- skewness(LeveeFailures$ChannelWidth)
S16 <- skewness(Retirement$SRA)
S17 <- skewness(CO2Hawaii$CO2)
S18 <- skewness(Faces$SHR)
S19 <- skewness(Kids198$Weight)
S20 <- skewness(BirdNest$Length)
```



```{r}
S21 <- skewness(HawkTail$Tail)
S22 <- skewness(AppleStock$Price)
S23 <- skewness(Kershaw$StartSpeed)
S24 <- skewness(SeaIce$Extent)
S25 <- skewness(TomlinsonRush$Yards)
S26 <- skewness(BlueJays$BillDepth)
S27 <- skewness(WalkTheDogs$Kcal)
S28 <- skewness(SeaSlugs$Percent)
S29 <- skewness(Dinosaurs$Iridium)
S30 <- skewness(Putts1$Length)
```

```{r}
S31 <- skewness(s_norm$value)
S32 <- skewness(m_norm$value)
S33 <- skewness(l_norm$value)
S34 <- skewness(s_right$value)
S35 <- skewness(m_right$value)
S36 <- skewness(l_right$value)
S37 <- skewness(s_left$value)
S38 <- skewness(m_left$value)
S39 <- skewness(l_left$value)
```



```{r}
skewness <- c(S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11, S12, S13, S14, S15, S16, S17, S18, S19, S20, S21, S22, S23, S24, S25, S26, S27, S28, S29, S30, S31, S32, S33, S34, S35, S36, S37, S38, S39)
```


```{r}

```


