---
title: "finalAnalysis_tina"
author: "Tina Liu"
date: "2020/1/20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Stat2Data)
library(mosaic)
library(car)
library(outliers)
library(tidyverse)
library(sn)
``` 

```{r}
record <- read_csv("WT Data Record2.csv")
```

```{r}
record
```


```{r}
record <- record %>%
  filter(!is.na(N)) %>%
  rename("setName" = "SetName",
         "size" = "Size",
         "n" = "N",
         "distribution" = "Distribution",
         "csq" = "CSQ",
         "cook" = "COOK",
         "iqr" = "IQR",
         "sd" = "SD",
         "bonf" = "BONF")
```



```{r}
record <- record %>%
  mutate(pcsq = csq / n,
         pcook = cook / n,
         piqr = iqr / n,
         psd = sd / n,
         pbonf = bonf / n)
```


```{r}
record %>%
  group_by(distribution) %>%
  summarize(mcsq = mean(pcsq),
            mcook = mean(pcook),
            miqr = mean(piqr),
            msd = mean(psd),
            mbonf = mean(pbonf))
```


```{r}
#record %>% ggplot(aes(x = N, y = SetName)) +
 # geom_point()
```

```{r}
record <- record %>% mutate(id = seq.int(nrow(record)))
```

```{r}
record
```


```{r}
rlm1 <- glm(pcsq~id, data=record)
summary(rlm1)
gf_point(pcsq ~id,
data = record) %>%
gf_smooth(linetype = "dashed",
color = "red") %>%
gf_lm(size = 1.5)

rlm2 <- glm(pcook~id, data=record)
summary(rlm2)
gf_point(pcook ~id,
data = record) %>%
gf_smooth(linetype = "dashed",
color = "red") %>%
gf_lm(size = 1.5)

rlm3 <- glm(piqr~id, data=record)
summary(rlm3)
gf_point(piqr ~id,
data = record) %>%
gf_smooth(linetype = "dashed",
color = "red") %>%
gf_lm(size = 1.5)

rlm4 <- glm(psd~id, data=record)
summary(rlm4)
gf_point(psd ~id,
data = record) %>%
gf_smooth(linetype = "dashed",
color = "red") %>%
gf_lm(size = 1.5)

rlm5 <- glm(pbonf~id, data=record)
summary(rlm5)
gf_point(pbonf ~id,
data = record) %>%
gf_smooth(linetype = "dashed",
color = "red") %>%
gf_lm(size = 1.5)
```

```{r}
iqvsd <- glm(piqr~psd, data=record)
summary(iqvsd)
gf_point(piqr ~psd,
data = record) %>%
gf_smooth(linetype = "dashed",
color = "red") %>%
gf_lm(size = 1.5)
```


```{r}
record %>%
  group_by(distribution) %>%
  ggplot(aes(x = distribution, y = pcsq)) +
  geom_boxplot()
```

```{r}
record
```

```{r}
record %>%
  ggplot(aes(x = id)) +
  geom_line(aes(y = csq, color = "csq")) +
  geom_line(aes(y = cook, color = "cook")) +
  geom_line(aes(y = iqr, color = "iqr")) +
  geom_line(aes(y = sd, color = "sd")) +
  geom_line(aes(y = bonf, color = "bonf")) +
  scale_color_manual( 
    name = "Method",
    values = c("csq"= "black", "cook" = "blue", "iqr" = "red", "sd" = "green", "bonf" = "orange"))
```


```{r}
record %>%
  filter(id != 5 & id != 23 & id != 1) %>%
  ggplot(aes(x = id)) +
  geom_line(aes(y = csq, color = "csq")) +
  geom_line(aes(y = cook, color = "cook")) +
  geom_line(aes(y = iqr, color = "iqr")) +
  geom_line(aes(y = sd, color = "sd")) +
  geom_line(aes(y = bonf, color = "bonf")) +
  scale_color_manual( 
    name = "Method",
    values = c("csq"= "black", "cook" = "blue", "iqr" = "red", "sd" = "green", "bonf" = "orange"))
```

```{r}
record %>%
  filter(id != 5 & id != 23 & id != 1) %>%
  ggplot(aes(x = id)) +
  geom_point(aes(y = csq, color = "csq")) +
  geom_point(aes(y = cook, color = "cook")) +
  geom_point(aes(y = iqr, color = "iqr")) +
  geom_point(aes(y = sd, color = "sd")) +
  geom_point(aes(y = bonf, color = "bonf")) +
  scale_color_manual( 
    name = "Method",
    values = c("csq"= "black", "cook" = "blue", "iqr" = "red", "sd" = "green", "bonf" = "orange"))
```



```{r}
record %>%
  ggplot(aes(x = id)) +
  geom_line(aes(y = pcsq, color = "csq")) +
  geom_line(aes(y = pcook, color = "cook")) +
  geom_line(aes(y = piqr, color = "iqr")) +
  geom_line(aes(y = psd, color = "sd")) +
  geom_line(aes(y = pbonf, color = "bonf")) +
  scale_color_manual( 
    name = "Method",
    values = c("csq"= "black", "cook" = "blue", "iqr" = "red", "sd" = "green", "bonf" = "orange"))
```


```{r}
record
```


```{r}
a1 <- aov(iqvsd)
summary(a1)
```




